repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run ruff
        entry: uv run ruff check .
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: Run pytest
        entry: uv run pytest
        language: system
        pass_filenames: false